(#6830) Fix 1.9 where "string"[:sym] no longer returns nil
Not sure why event resources are getting assigned strings, but indexing
into a string with a symbol in Ruby 1.9 raises a TypeError

  TypeError: can't convert Symbol into Integer