(#6830) Fix MD5 handling to work with Ruby 1.9
In Ruby 1.9 you have to require 'digest/md5' instead of just 'md5'.  The
following irb sessions from each version of Ruby should explain the changes in
how MD5 is used between Ruby versions and why this patch was made.

ruby-1.9.2-p136 :001 > require 'md5'
LoadError: no such file to load -- md5
ruby-1.9.2-p136 :002 > require 'digest/md5'
 => true
ruby-1.9.2-p136 :003 > Digest::MD5.hexdigest('mystring')
 => "169319501261c644a58610f967e8f9d0"
ruby-1.9.2-p136 :004 > Digest::MD5.new('mystring')
 => #<Digest::MD5: d41d8cd98f00b204e9800998ecf8427e>

ruby-1.8.7-p330 :001 > require 'digest/md5'
 => []
ruby-1.8.7-p330 :002 > require 'md5'
 => ["MD5"]
ruby-1.8.7-p330 :003 > Digest::MD5.hexdigest('mystring')
 => "169319501261c644a58610f967e8f9d0"
ruby-1.8.7-p330 :004 > MD5.new('mystring')
 => #<MD5: 169319501261c644a58610f967e8f9d0>
ruby-1.8.7-p330 :005 > MD5.new('mystring').to_s
 => "169319501261c644a58610f967e8f9d0"
ruby-1.8.7-p330 :006 > Digest::MD5.new('mystring')
ArgumentError: wrong number of arguments (1 for 0)